version: 2.1

orbs:
  jahia-modules-orb: jahia/jahia-modules-orb@1

# Parameters are available across the entire config file and can be used with this syntax: << pipeline.parameters.THE_PARAMETER >>
# Avoid using project-specific variables in the jobs or steps.
# Instead, declare those as pipeline parameters (At the top of the config file).
# This eases portability of the config file across different modules
parameters:
  AUDITCI_LEVEL:
    type: string
    default: "critical"
  TESTS_PATH:
    type: string
    default: "tests/"
  TESTS_IMAGE:
    type: string
    default: "jahia/jcontent"
  TESTRAIL_MILESTONE:
    type: string
    default: "Default"
  MODULE_ID:
    type: string
    default: "jContent"
  TESTRAIL_PROJECTNAME:
    type: string
    default: "jContent Module"
  GITHUB_SLUG:
    type: string
    default: "jahia/jContent"
  PRIMARY_RELEASE_BRANCH:
    type: string
    default: "master" # main or master ? set the branch for the main release
  JAHIA_IMAGE:
    type: string
    default: "jahia/jahia-discovery-dev:8-SNAPSHOT"
  RELEASE_ID:
    type: string
    default: ""
  RELEASE_VERSION:
    type: string
    default: ""
  IS_RELEASE:
    type: boolean
    default: false
  UPDATE_SIGNATURE:
    type: boolean
    default: false
  SSH_KEY_FINGERPRINT:
    type: string
    default: "a5:8b:fd:fb:1b:38:af:66:3d:fb:1e:84:22:e1:8a:e1"
  SHOULD_SKIP_ARTIFACTS:
    type: boolean
    default: true
  SHOULD_SKIP_TESTRAIL:
    type: boolean
    default: true
  SHOULD_SKIP_NOTIFICATIONS:
    type: boolean
    default: true
  SHOULD_SKIP_ZENCREPES:
    type: boolean
    default: true
  TESTS_MANIFEST: # Manifest to be executed by the test container when triggered from an API call
    type: string
    default: ""
  IS_ROLLBACK:
    type: boolean
    default: false
  IS_MANUAL_TESTRUN: # Was the workflow triggered by an API call ?
    type: boolean
    default: false

jobs:
  where-am-i:
    steps:
      - run: pwd

workflows:
  # On code change is executed each time new code is pushed to a branch
  # Current project configuration in circleci only builds on PR + main, so effectively this is only being executed
  on-code-change:
    unless:
      or:
        - << pipeline.parameters.IS_RELEASE >>
        - << pipeline.parameters.IS_ROLLBACK >>
        - << pipeline.parameters.UPDATE_SIGNATURE >>
        - << pipeline.parameters.IS_MANUAL_TESTRUN >>
    jobs:
      - jahia-modules-orb/initialize
      # - jahia-modules-orb/build:
      #     context: QA_ENVIRONMENT
      #     requires:
      #       - jahia-modules-orb/initialize
            # - jahia-modules-orb/update-signature
      - where-am-i
      - jahia-modules-orb/integration-tests-machine:
          # requires:
            # - jahia-modules-orb/build
          context: QA_ENVIRONMENT
          jahia_image: << pipeline.parameters.JAHIA_IMAGE >>
          tests_manifest: << pipeline.parameters.TESTS_MANIFEST >>
          module_id: << pipeline.parameters.MODULE_ID >>
          testrail_project: << pipeline.parameters.TESTRAIL_PROJECTNAME >>
          testrail_milestone: << pipeline.parameters.TESTRAIL_MILESTONE >>
          should_skip_artifacts: << pipeline.parameters.SHOULD_SKIP_ARTIFACTS >>
          should_skip_testrail: << pipeline.parameters.SHOULD_SKIP_TESTRAIL >>
          should_skip_notifications: << pipeline.parameters.SHOULD_SKIP_NOTIFICATIONS >>
          should_skip_zencrepes: << pipeline.parameters.SHOULD_SKIP_ZENCREPES >>
